# Data Cleaning Pipeline

In [1]:
%load_ext autoreload
%autoreload 2

from io_utils import *
from clean import *

import matplotlib.pyplot as plt

## Load the Data

In [2]:
df = load_raw_data()
df.head()

,PatNum,EmplType,Certification,InjuryMech,High_impact_InjSev,Amnesia_verb,LOCSeparate,LocLen,Seiz,SeizOccur,...,Finding20,Finding21,Finding22,Finding23,DeathTBI,HospHead,HospHeadPosCT,Intub24Head,Neurosurgery,PosIntFinal
0,1,3.0,3,11.0,2.0,0.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
1,2,5.0,3,8.0,2.0,0.0,0.0,92.0,0.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0
2,3,5.0,3,5.0,2.0,NaN,NaN,92.0,NaN,92.0,...,0,0,0,0,0.0,1.0,0,0.0,0.0,0.0
3,4,5.0,3,6.0,1.0,91.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
4,5,3.0,3,12.0,2.0,91.0,0.0,92.0,0.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0

In [3]:
# print the basic information of the dataset
print("Dataset shape:", df.shape)
print("\nDataset columns:", df.columns)
print("\nData types of each column:")
print(df.dtypes)

# check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())
print("\nPercentage of missing values per column:")
print((df.isnull().sum() / len(df)) * 100)

# check for duplicates
print("\nUnique values per column:")
print(df.nunique())

# check for summary statistics of numerical columns
print("\nSummary statistics:")
print(df.describe())

Dataset shape: (43399, 125)

Dataset columns: Index(['PatNum', 'EmplType', 'Certification', 'InjuryMech',
       'High_impact_InjSev', 'Amnesia_verb', 'LOCSeparate', 'LocLen', 'Seiz',
       'SeizOccur',
       ...
       'Finding20', 'Finding21', 'Finding22', 'Finding23', 'DeathTBI',
       'HospHead', 'HospHeadPosCT', 'Intub24Head', 'Neurosurgery',
       'PosIntFinal'],
      dtype='str', length=125)

Data types of each column:
PatNum                  int64
EmplType              float64
Certification           int64
InjuryMech            float64
High_impact_InjSev    float64
                       ...
HospHead              float64
HospHeadPosCT           int64
Intub24Head           float64
Neurosurgery          float64
PosIntFinal           float64
Length: 125, dtype: object

Missing values per column:
PatNum                  0
EmplType               18
Certification           0
InjuryMech            301
High_impact_InjSev    334
                     ...
HospHead                3
HospHeadPosCT           0
Intub24Head             4
Neurosurgery            1
PosIntFinal            20
Length: 125, dtype: int64

Percentage of missing values per column:
PatNum                0.000000
EmplType              0.041476
Certification         0.000000
InjuryMech            0.693564
High_impact_InjSev    0.769603
                        ...
HospHead              0.006913
HospHeadPosCT         0.000000
Intub24Head           0.009217
Neurosurgery          0.002304
PosIntFinal           0.046084
Length: 125, dtype: float64

Unique values per column:
PatNum                43399
EmplType                  5
Certification             5
InjuryMech               13
High_impact_InjSev        3
                      ...
HospHead                  2
HospHeadPosCT             2
Intub24Head               2
Neurosurgery              2
PosIntFinal               2
Length: 125, dtype: int64

Summary statistics:
             PatNum      EmplType  Certification    InjuryMech  \
count  43399.000000  43381.000000   43399.000000  43098.000000
mean   21700.000000      3.996750       3.984055     13.905146
std    12528.356503      1.161454      11.178135     22.697257
min        1.000000      1.000000       1.000000      1.000000
25%    10850.500000      3.000000       2.000000      6.000000
50%    21700.000000      5.000000       3.000000      8.000000
75%    32549.500000      5.000000       3.000000     10.000000
max    43399.000000      5.000000      90.000000     90.000000

       High_impact_InjSev  Amnesia_verb   LOCSeparate        LocLen  \
count        43065.000000  41103.000000  41507.000000  40843.000000
mean             1.986555     32.888159      0.213313     82.578532
std              0.565865     43.603687      0.514553     27.517329
min              1.000000      0.000000      0.000000      1.000000
25%              2.000000      0.000000      0.000000     92.000000
50%              2.000000      0.000000      0.000000     92.000000
75%              2.000000     91.000000      0.000000     92.000000
max              3.000000     91.000000      2.000000     92.000000

               Seiz     SeizOccur  ...     Finding20     Finding21  \
count  42487.000000  43328.000000  ...  43399.000000  43399.000000
mean       0.014193     90.890694  ...     58.296643     58.296551
std        0.118286      9.949818  ...     44.326113     44.326233
min        0.000000      1.000000  ...      0.000000      0.000000
25%        0.000000     92.000000  ...      0.000000      0.000000
50%        0.000000     92.000000  ...     92.000000     92.000000
75%        0.000000     92.000000  ...     92.000000     92.000000
max        1.000000     92.000000  ...     92.000000     92.000000

          Finding22     Finding23      DeathTBI      HospHead  HospHeadPosCT  \
count  43399.000000  43399.000000  43391.000000  43396.000000   43399.000000
mean      58.296850     58.296297      0.001521      0.020002       0.015968
std       44.325843     44.326564      0.038971      0.140008       0.125353
min        0.000000      0.000000      0.000000      0.000000       0.000000
25%        0.000000      0.000000      0.000000      0.000000       0.000000
50%       92.000000     92.000000      0.000000      0.000000       0.000000
75%       92.000000     92.000000      0.000000      0.000000       0.000000
max       92.000000     92.000000      1.000000      1.000000       1.000000

        Intub24Head  Neurosurgery   PosIntFinal
count  43395.000000  43398.000000  43379.000000
mean       0.004401      0.004609      0.017589
std        0.066198      0.067730      0.131454
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000
max        1.000000      1.000000      1.000000

[8 rows x 125 columns]

## Data Cleaning: Phase 0 — Column Renaming

In [4]:
df_renamed = rename_columns(df)
summarize_rename(df, df_renamed)

{'n_rows_before': 43399,
 'n_cols_before': 125,
 'n_rows_after': 43399,
 'n_cols_after': 125,
 'unchanged_cols': []}

# Data Cleaning: Phase 1 — Structural Validation

### Convert Type

In [5]:
non_numeric_columns = identify_non_numeric_columns(df_renamed)
non_numeric_columns

[]

### Validate Allowed Values

In [6]:
issues = validate_allowed_values(df_renamed)
issues

Empty DataFrame
Columns: [column, invalid_value, n, examples]
Index: []

### Check Duplicate Row

In [7]:
dup_summary = check_duplicates(df_renamed, key_col="patient_id")
dup_summary

{'n_dup_key_rows': 0, 'n_dup_key_values': 0, 'n_dup_rows': 0}

## Data Cleaning -- Inconsistency Check

In [8]:
issues = summarize_consistency(df_renamed)
save_table(issues, "consistency_issues.csv")
issues

,group,rule,n_inconsistent,pct_rows,examples
0,Parent-child Logic,loss_of_consciousness=1 but loc_duration missing,1536,3.539252,"[49, 54, 65, 92, 142]"
1,Parent-child Logic,ct_planned=1 but no CT reason is marked,1406,3.239706,"[67, 79, 94, 141, 144]"
2,Parent-child Logic,headache=1 but headache_onset missing,1332,3.069195,"[7, 11, 28, 166, 327]"
3,Parent-child Logic,headache=1 but headache_severity missing,1044,2.405585,"[28, 60, 82, 166, 194]"
4,Parent-child Logic,scalp_hematoma=1 but hematoma_size missing,742,1.709717,"[163, 330, 335, 351, 423]"
5,Parent-child Logic,ams=1 but no AMS subtype marked,615,1.417083,"[167, 267, 304, 412, 539]"
6,Parent-child Logic,trauma_above_clavicles=1 but no location marked,302,0.695869,"[11, 21, 196, 279, 280]"
7,Parent-child Logic,scalp_hematoma=1 but hematoma_location missing,211,0.486186,"[466, 596, 718, 1148, 1369]"
8,CT & Outcomes,severe outcome component but citbi!=1,160,0.368672,"[2, 304, 312, 466, 497]"
9,Parent-child Logic,seizure=1 but seizure_duration missing,117,0.269591,"[75, 477, 670, 754, 1481]"
10,Parent-child Logic,other_substantial_injury=1 but no specific inj...,74,0.170511,"[326, 897, 2085, 2158, 2192]"
11,Parent-child Logic,seizure=1 but seizure_timing missing,71,0.163598,"[75, 477, 670, 754, 969]"
12,Parent-child Logic,palpable_skull_fracture=1 but depressed missing,55,0.126731,"[876, 1848, 2439, 2718, 3036]"
13,Parent-child Logic,vomiting=1 but all vomiting details missing,54,0.124427,"[570, 708, 778, 1465, 2174]"
14,Parent-child Logic,ct_sedation=1 but no sedation detail marked,32,0.073734,"[1243, 4663, 4805, 5600, 7834]"
15,Parent-child Logic,neuro_deficit=1 but no specific deficit marked,19,0.043780,"[7900, 9256, 15095, 16759, 18570]"
16,Parent-child Logic,basilar_signs=1 but no specific basilar sign m...,18,0.041476,"[4078, 4651, 4938, 5717, 7063]"
17,Cross-field Logic,gcs_total != gcs_eye + gcs_verbal + gcs_motor,2,0.004608,"[12931, 24761]"
18,CT & Outcomes,ct_done=0 but a CT finding is marked,0,0.000000,[]
19,CT & Outcomes,tbi_on_ct=0 but non-skull CT finding marked,0,0.000000,[]
20,CT & Outcomes,tbi_on_ct=1 but ct_done=0,0,0.000000,[]
21,Cross-field Logic,age_months and age_years disagree by > 1 year,0,0.000000,[]
22,Cross-field Logic,age_two_plus=1 but age_years>=2,0,0.000000,[]
23,Cross-field Logic,age_two_plus=2 but age_years<2,0,0.000000,[]
24,Cross-field Logic,gcs_total<14 but gcs_group!=1,0,0.000000,[]
25,Cross-field Logic,gcs_total>=14 but gcs_group!=2,0,0.000000,[]
26,Parent-child Logic,ams=0 but an AMS subtype is marked,0,0.000000,[]
27,Parent-child Logic,basilar_signs=0 but a specific basilar sign is...,0,0.000000,[]
28,Parent-child Logic,ct_planned=0 but a CT reason is marked,0,0.000000,[]
29,Parent-child Logic,ct_sedation=0 but sedation detail marked,0,0.000000,[]
30,Parent-child Logic,headache=0 but headache_onset recorded,0,0.000000,[]
31,Parent-child Logic,headache=0 but headache_severity recorded,0,0.000000,[]
32,Parent-child Logic,loss_of_consciousness=0 but loc_duration recorded,0,0.000000,[]
33,Parent-child Logic,neuro_deficit=0 but a specific deficit is marked,0,0.000000,[]
34,Parent-child Logic,other_substantial_injury=0 but specific injury...,0,0.000000,[]
35,Parent-child Logic,palpable_skull_fracture=0 but depressed=1,0,0.000000,[]
36,Parent-child Logic,scalp_hematoma=0 but hematoma_location recorded,0,0.000000,[]
37,Parent-child Logic,scalp_hematoma=0 but hematoma_size recorded,0,0.000000,[]
38,Parent-child Logic,seizure=0 but seizure_duration recorded,0,0.000000,[]
39,Parent-child Logic,seizure=0 but seizure_timing recorded,0,0.000000,[]
40,Parent-child Logic,trauma_above_clavicles=0 but location marked,0,0.000000,[]
41,Parent-child Logic,vomiting=0 but vomiting_count recorded,0,0.000000,[]
42,Parent-child Logic,vomiting=0 but vomiting_last recorded,0,0.000000,[]
43,Parent-child Logic,vomiting=0 but vomiting_onset recorded,0,0.000000,[]
44,Ranges & Coding,"age_months outside [0, 240]",0,0.000000,[]
45,Ranges & Coding,"age_years outside [0, 18]",0,0.000000,[]
46,Ranges & Coding,"gcs_eye outside [1, 4]",0,0.000000,[]
47,Ranges & Coding,"gcs_motor outside [1, 6]",0,0.000000,[]
48,Ranges & Coding,"gcs_total outside [3, 15]",0,0.000000,[]
49,Ranges & Coding,"gcs_verbal outside [1, 5]",0,0.000000,[]

## Data Cleaning -- Missing Value

### Missing Overview

In [9]:
missing_na = df_renamed.isna().mean().sort_values(ascending=False)
missing_na.head(20)

dizziness                    0.368027
ethnicity                    0.367889
acting_normal                0.076845
race                         0.073919
loc_duration                 0.058895
observed_in_ed               0.054748
amnesia_present              0.052904
loss_of_consciousness        0.043595
drug_or_alcohol_suspicion    0.041890
headache_onset               0.030692
gcs_motor                    0.030185
gcs_verbal                   0.029909
gcs_eye                      0.029678
headache_severity            0.024056
vomiting_last                0.022858
ct_sedation                  0.021060
posttraumatic_seizure        0.021014
scalp_hematoma_size          0.017097
neuro_deficit                0.015208
headache                     0.015023
dtype: float64

In [10]:
special_missing = summarize_special_missing(df_renamed)
special_missing.sort_values("proportion", ascending=False).head(20)

                               column  code  proportion
20  palpable_skull_fracture_depressed    92    0.994839
21               basilar_hemotympanum    92    0.990875
22                   basilar_otorrhea    92    0.990875
24  basilar_retroauricular_ecchymosis    92    0.990875
25                 basilar_rhinorrhea    92    0.990875
23     basilar_periorbital_ecchymosis    92    0.990875
7                      seizure_timing    92    0.986106
8                    seizure_duration    92    0.986106
66                  ct_sedation_other    92    0.984931
65           ct_sedation_tech_request    92    0.984931
64                    ct_sedation_age    92    0.984931
63               ct_sedation_agitated    92    0.984931
38                neuro_deficit_other    92    0.984147
36              neuro_deficit_cranial    92    0.984147
35              neuro_deficit_sensory    92    0.984147
34                neuro_deficit_motor    92    0.984147
37               neuro_deficit_reflex    92    0.984147
40         other_injury_or_laceration    92    0.894767
39             other_injury_extremity    92    0.894767
43               other_injury_abdomen    92    0.894767

In [11]:
total_missing = summarize_total_missing(df_renamed)
total_missing.head(20)

                               column  total_missing_proportion
35  palpable_skull_fracture_depressed                  0.996106
38               basilar_hemotympanum                  0.990875
39                   basilar_otorrhea                  0.990875
40     basilar_periorbital_ecchymosis                  0.990875
41  basilar_retroauricular_ecchymosis                  0.990875
42                 basilar_rhinorrhea                  0.990875
10                   seizure_duration                  0.988802
9                      seizure_timing                  0.987742
89                  ct_sedation_other                  0.984931
88           ct_sedation_tech_request                  0.984931
87                    ct_sedation_age                  0.984931
86               ct_sedation_agitated                  0.984931
57               neuro_deficit_reflex                  0.984147
54                neuro_deficit_motor                  0.984147
56              neuro_deficit_cranial                  0.984147
55              neuro_deficit_sensory                  0.984147
58                neuro_deficit_other                  0.984147
7                        loc_duration                  0.901242
60             other_injury_extremity                  0.894767
61         other_injury_or_laceration                  0.894767

### Check Structural Missing

In [12]:
pd.crosstab(
    df_renamed["posttraumatic_seizure"],
    df_renamed["seizure_timing"]
)

seizure_timing         1.0   2.0   3.0    92.0
posttraumatic_seizure
0.0                       0     0     0  41884
1.0                     253   210    69      0

### Check Informative Missing

In [13]:
pd.crosstab(
    df_renamed["age_two_plus"],
    df_renamed["dizziness"].isna()
)

dizziness     False  True
age_two_plus
1              1360   9544
2             26067   6428

In [14]:
pd.crosstab(df_renamed["dizziness"].isna(),
            df_renamed["citbi"],
            normalize="index")

citbi           0.0       1.0
dizziness
False      0.992924  0.007076
True       0.964355  0.035645

### Check MCAR

In [15]:
# ethnicity missing vs outcome
pd.crosstab(df_renamed["ethnicity"].isna(),
            df_renamed["citbi"],
            normalize="index")

citbi          0.0      1.0
ethnicity
False      0.98432  0.01568
True       0.97913  0.02087

In [16]:

pd.crosstab(df_renamed["ethnicity"].isna(),
            df_renamed["gcs_group"],
            normalize="index")

gcs_group         1         2
ethnicity
False      0.019903  0.980097
True       0.026494  0.973506

### Handle Missing Values

In [17]:
df_cleaned = handle_missing_values(df_renamed)

In [18]:
print("Before cleaning:")
print("Shape:", df_renamed.shape)
print("After cleaning:")
print("Shape:", df_cleaned.shape)

Before cleaning:
Shape: (43399, 125)
After cleaning:
Shape: (43399, 125)

## Data Cleaning -- Column Reduction

In [19]:
plan = build_drop_plan(
    df_cleaned,
    timepoint="pre_ct",
    drop_ethnicity=True,
    high_missing_threshold=0.95,
    keep_age="age_years",
    keep_gcs="gcs_total",
)

df_drop, dropped_cols = apply_drop_plan(df_cleaned, plan)
df_drop.shape

(43399, 75)

### Data Cleaning -- Comparison with Published Rates

In [20]:
mine, paper = compare_with_kuppermann_2009(df_cleaned)
save_table(mine, "my_data_cleaning_summary.csv")
save_table(paper, "paper_data_summary.csv")
mine, paper

(                             my_ct_done_%  my_tbi_on_ct_among_ct_%  \
 Age <2 (my data, GCS 14-15)         31.05                     8.53
 Age ≥2 (my data, GCS 14-15)         36.75                     4.28

                              my_citbi_%  my_neurosurgery_%
 Age <2 (my data, GCS 14-15)        0.91               0.18
 Age ≥2 (my data, GCS 14-15)        0.88               0.13  ,
                      paper_tbi_on_ct_%  paper_citbi_%  paper_neurosurgery_%
 Age <2 (Derivation)                8.1            0.9                   0.2
 Age <2 (Validation)                9.8            1.1                   0.2
 Age ≥2 (Derivation)                4.1            0.9                   0.1
 Age ≥2 (Validation)                5.2            1.0                   0.2)

In [21]:
df = load_raw_data()
df_cleaned = clean_data(df)
df_cleaned_without_drops = clean_data_without_dropping(df)


save_table(df_cleaned, "df_cleaned.csv")
save_table(df_cleaned_without_drops, "df_cleaned_without_drops.csv")

PosixPath('/Users/ren/Library/CloudStorage/OneDrive-Personal/2025-26 UC Berkeley/2025-26 Term 2/STAT 214 Data Analysis and Machine Learning for Real-World Decision Making/stat-214/lab1/data/df_cleaned_without_drops.csv')